- name: add apt key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com
    id: F1656F24C74CD1D8

- name: add repository
  apt_repository:
    repo: deb [arch=amd64,i386,ppc64el] http://ftp.utexas.edu/mariadb/repo/10.1/ubuntu xenial main
    state: present

- name: apt update
  apt:
    update_cache: yes

- name: install mariadb-server
  apt:
    name: mariadb-server
    state: present
    install_recommends: false
  register: mariadb_server_register_install_status

- name: copy galera.cnf
  template:
    src: ../files/galera.cnf
    dest: /etc/mysql/conf.d/galera.cnf

- name: stop mysql service in other nodes
  service: name=mysql state=stopped
  when: ansible_play_hosts[0] != inventory_hostname

- name: stop mysql service on first node
  service: name=mysql state=stopped
  when: ansible_play_hosts[0] == inventory_hostname

- name: Start mysql on first node
  shell: galera_new_cluster
  when: ansible_play_hosts[0] == inventory_hostname

- name: Start mysql in other nodes
  service: name=mysql state=started
  when: ansible_play_hosts[0] != inventory_hostname
