- import_tasks: ../common/tasks/main.yml

- name: install nginx
  apt: pkg={{ item }} state=present
  with_items:
  - nginx
  register: apt_status
  until: apt_status is success
  delay: 5
  retries: 24
  tags:
  - install

- name: config nginx.cfg
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: restart-nginx
  tags:
  - install
  - config

- name: remove nginx
  apt: pkg={{ item }} state=absent purge=true
  with_items:
  - nginx
  tags:
  - remove

- name: stop nginx
  systemd: name=nginx state=stopped
  tags:
  - stop

- name: start nginx
  systemd: name=nginx state=started
  tags:
  - start

- name: restart nginx
  systemd: name=nginx state=restarted
  tags:
  - restart


- name: telegraf list nginx ports
  set_fact: nginx_urls="{% for k, item in servers.iteritems() %}http://localhost:{% set listen = item.listen | string %}{{ listen.split(' ')[0] }}/nginx_status{% if not loop.last %},{% endif %}{% endfor %}"
  tags:
  - install
  - config

- name: telegraf add nginx monitoring
  ini_file:
    path: /etc/telegraf/telegraf.conf
    section: "[inputs.nginx]"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { option: "urls", value: "[{{ nginx_urls }}]" } 
  notify: restart-telegraf
  when: telegraf_conf.stat.exists
  tags:
  - install
  - config

- name: telegraf remove nginx monitoring
  ini_file:
    path: /etc/telegraf/telegraf.conf
    section: "[inputs.nginx]"
    state: absent
  when: telegraf_conf.stat.exists
  tags:
  - remove

