- import_tasks: ../common/tasks/main.yml

- name: install nginx
  apt: pkg={{ item }} state=present
  with_items:
  - nginx
  register: apt_status
  until: apt_status|success
  delay: 5
  retries: 24
  tags:
  - install

- name: config nginx.cfg
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: restart-nginx
  tags:
  - install
  - config

- name: remove nginx
  apt: pkg={{ item }} state=absent purge=true
  with_items:
  - nginx
  tags:
  - remove

- name: stop nginx
  systemd: name=nginx state=stopped
  tags:
  - stop

- name: start nginx
  systemd: name=nginx state=started
  tags:
  - start

- name: restart nginx
  systemd: name=nginx state=restarted
  tags:
  - restart
