- import_tasks: ../common/tasks/main.yml

- name: install nginx
  apt: pkg={{ item }} state=present
  with_items:
  - nginx
  tags:
  - install

- name: config nginx.conf
  template: 
    src: nginx.conf.j2 
    dest: /etc/nginx/nginx.conf 
  notify: restart-nginx
  tags:
  - install
  - config

- name: remove nginx
  apt: pkg={{ item }} state=absent purge=true
  with_items:
  - nginx
  tags:
  - remove

