- import_tasks: ../common/tasks/main.yml

- name: install haproxy
  apt: pkg={{ item }} state=present
  with_items:
  - haproxy
  tags:
  - install

- name: Ensure directory exists for ssl
  file:
    path: /etc/haproxy/cert/
    state: directory
  tags:
  - install
  - cert

- name: copy certificate to remote hosts
  copy:
    src: "{{ item.value.ssl_cert_file }}"    
    dest: /etc/haproxy/cert/{{ item.key }}.one
    owner: haproxy
    group: haproxy
    mode: 0644
    backup: yes
  with_dict: "{{ webs | default({}) }}"
  tags:
  - install
  - cert

- name: config haproxy.cfg
  template: 
    src: haproxy.cfg.j2 
    dest: /etc/haproxy/haproxy.cfg
  notify: restart-haproxy
  tags:
  - install
  - config

- name: remove haproxy
  apt: pkg={{ item }} state=absent purge=true
  with_items:
  - haproxy
  tags:
  - remove
