limits_setting:
# update file descriptors size
  - "* soft nofile 10000000"
  - "* hard nofile 10000000"
  - root soft nofile 10000000
  - root hard nofile 10000000

sysctl_setting:
# update file descriptors size
  fs.file-max: 10000000
  fs.nr_open: 10000000
# reduce memory for TCP buffer
  net.ipv4.tcp_mem: 786432 1697152 1945728
  net.ipv4.tcp_rmem: 4096 4096 16777216
  net.ipv4.tcp_wmem: 4096 4096 16777216
