# By  GunSik Choi(gschoi@crossent.com)

- import_tasks: ../common/tasks/main.yml

- name: include release specific variables
  include_vars: "{{ ansible_distribution_release }}.yml"
  tags: [install, remove]

- name: apt-key add
  apt_key:
    id: "{{ item.id | default(None) or omit }}"
    keyserver: "{{ item.keyserver | default(None) or omit }}"
    url: "{{ item.url | default(None) or omit }}"
    state: "{{ item.state }}"
  with_items: "{{ _apt_key }}"
  tags: install

- name: apt-add-repository
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
  with_items: "{{ _apt_repository }}"
  tags: install

- name: remove lock files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - /var/lib/apt/lists/lock
  - /var/cache/apt/archives/lock
  - /var/lib/dpkg/lock 
  - /var/lib/dpkg/updates/*
  tags:
  - install

- name: apt-get install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    force: yes
  with_items: "{{ _apt }}"
  register: apt_status
  until: apt_status is success
  delay: 5
  retries: 48
  tags: install

- name: create required mysql directories
  file: path={{ item }} state=directory owner=mysql group=mysql
  with_items:
    - /etc/mysql/conf.d
    - /var/log/mysql
  tags:
    - install

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    #- { src: "galera.cnf.j2", dest: "/etc/mysql/conf.d/galera.cnf" }
    - { src: "mariadb.cnf.j2", dest: "/etc/mysql/conf.d/mariadb.cnf" }
    - { src: "my.cnf.j2", dest: "/etc/mysql/my.cnf" }
  tags:
  - install
  - config

- name: start service
  service:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { name: "mysql", state: "started" }
  register: start_service_result
  ignore_errors: yes
  tags: install

#- name: debug
#  debug:
#    var: start_service_result
#  tags: install

- name: remove root .my.cnf
  file: path=/root/.my.cnf state=absent
  tags: install

- name: disable mysql anonymous access
  shell: mysql -NBe "DELETE FROM mysql.user WHERE User = ''"
  when:
    - start_service_result.results[0].state == "started"
  register: disable_anonymous_access_result
  changed_when: disable_anonymous_access_result.rc != 0
  ignore_errors: yes
  run_once: true
  tags: install

- name: setup mysql root password
  shell: mysql -NBe "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('{{ mysql_root_pass }}')"
  when:
    - start_service_result.results[0].state == "started"
    - mysql_root_pass is string
  register: setup_root_password_result
  changed_when: setup_root_password_result.rc != 0
  ignore_errors: yes
  run_once: true
  tags: install

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: ".my.cnf.j2", dest: "/root/.my.cnf",  owner: "root", group: "root", mode: "0600" }
  when:
    - start_service_result.results[0].state == "started"
    - mysql_root_pass is string
    - setup_root_password_result.rc == 0
  ignore_errors: yes
  tags: install

################################
# Find galera master : max seqno 
###############################
- name: get galera state data 
  shell: cat /var/lib/mysql/grastate.dat | grep seqno | awk '{print $2}'
  register: state_file
  tags: 
  - bootstrap
  - install
  - config
  - start
  - restart

- name: set galera seqno
  set_fact: seqno="{% if state_file.stdout != '' %} {{ state_file.stdout | int + 1 }} {% else %} {{ 0 }} {% endif %}"
  tags: 
  - bootstrap
  - install
  - config
  - start
  - restart

# transform to collection 
- name: merge seqno
  set_fact: seqnos="{{ seqnos | default([]) }} + [ {{ hostvars[item]['seqno'] }}  ]"
  with_items: "{{ groups['mariadb'] }}"
  tags: 
  - bootstrap
  - install
  - config
  - start
  - restart

#- name: debug
#  debug: var=seqnos
#  tags: 
#  - bootstrap

- name: find max seqno value
  set_fact: seqno_max={{ seqnos | max }}
  tags: 
  - bootstrap
  - install
  - config
  - start
  - restart

#- name: debug
#  debug: var=seqno_max
#  tags: 
#  - bootstrap


- name: find galera master index
  set_fact: mysql_master_node={{ groups['mariadb'][item.0] }}
  #debug:
  #  msg: "{{ seqno_max }} {{ item.0 }}, {{item.1 }}, groups['mariadb'][ {{item.0 }} ]['inventory_hostname']"
  with_indexed_items: "{{ seqnos }}"
  when: item.1 == seqno_max|int and mysql_master_node is not defined
  tags: 
  - bootstrap
  - install
  - config
  - start
  - restart

#- name: debug
#  debug: var=mysql_master_node
#  tags: 
#  - bootstrap
#  - install
#  - config
#  - start
#  - restart

- name: enable to bootstrap
  replace:
    path: /var/lib/mysql/grastate.dat
    regexp: 'safe_to_bootstrap: 0'
    replace: 'safe_to_bootstrap: 1'
  when: state_file.stdout != ''
  tags: 
  - bootstrap
  - install
  - config
  - start
  - restart
   
################################
# Find galera master : end
###############################

- name: config bootstrap cluster - "{{ mysql_master_node }}"
  lineinfile: dest=/etc/mysql/my.cnf regexp="^wsrep_cluster_address = \"gcomm://" line="wsrep_cluster_address = \"gcomm://\"" state=present backrefs=yes
  when: hostvars[mysql_master_node].ansible_host == ansible_host 
  tags:
  - install
  - config
  - start
  - restart

- name: stop mysql services
  service: name=mysql state=stopped
  notify: force-stop-mysql
  changed_when: True
  tags:
  - install
  - config
  - remove
  - stop
  - start
  - restart

- name: bootstrap mysql service
  shell: service mysql start --wsrep-new-cluster
  when: hostvars[mysql_master_node].ansible_host == ansible_host 
  #run_once: true
  ignore_errors: yes
  tags:
  - install
  - config
  - start
  - restart

- name: create sstuser password
  shell: mysql -uroot -p{{ mysql_root_pass }} -NBe "CREATE USER 'sstuser'@'localhost' IDENTIFIED BY '{{ sstuser_pass }}'"
  when:
    - start_service_result.results[0].state == "started"
    - sstuser_pass is string
  register: sstuser_password_result
  changed_when: sstuser_password_result.rc != 0
  ignore_errors: yes
  run_once: true
  tags: install

- name: grant role to sstuser 
  shell: mysql -uroot -p{{ mysql_root_pass }} -NBe "GRANT RELOAD, LOCK TABLES, PROCESS, REPLICATION CLIENT ON *.* TO 'sstuser'@'localhost'"
  when:
    - start_service_result.results[0].state == "started"
    - sstuser_pass is string
  register: grant_sstuser_result
  changed_when: grant_sstuser_result.rc != 0
  ignore_errors: yes
  run_once: true
  tags: install

# reset root password: because root passwd gone away after starting galera cluster
- name: setup mysql root password
  shell: mysql -uroot -p{{ mysql_root_pass }} -NBe "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('{{ mysql_root_pass }}')"
  when:
    - start_service_result.results[0].state == "started"
    - mysql_root_pass is string
  register: setup_root_password_result
  changed_when: setup_root_password_result.rc != 0
  ignore_errors: yes
  run_once: true
  tags: install

- name: start mysql in other nodes
  service: name=mysql state=started 
  when: hostvars[mysql_master_node].ansible_host != ansible_host 
  tags:
  - install
  - config
  - start
  - restart

- name: copy master templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    #- { src: "galera.cnf.j2", dest: "/etc/mysql/conf.d/galera.cnf" }
    - { src: "mariadb.cnf.j2", dest: "/etc/mysql/conf.d/mariadb.cnf" }
    - { src: "my.cnf.j2", dest: "/etc/mysql/my.cnf" }
  when: hostvars[mysql_master_node].ansible_host == ansible_host 
  tags:
  - install
  - config
  - start
  - restart

- name: restart mysql on master node
  service: name=mysql state=restarted
  when: hostvars[mysql_master_node].ansible_host == ansible_host 
  tags:
  - install
  - config
  - start
  - restart

- name: check cluster size with command
  shell: mysql -uroot -p{{ mysql_root_pass }} -NBe "show status where Variable_name regexp 'wsrep_cluster_status|wsrep_cluster_size|wsrep_local_state_comment|wsrep_ready'"
  register: cluster_size
  tags:
  - status

- name: check service
  shell: ps aux | grep mysql | grep -v grep | awk '{print $2}'
  ignore_errors: yes
  changed_when: false
  register: service_status
  tags:
  - status

- name: status service
  debug: 
    msg: 
      - "mysql =>  {{ service_status.stdout != ''}} - {{ service_status.stdout }}"
      - "cluster_status =>  {{ cluster_size.stdout != '' }} - {{ cluster_size.stdout }}"
  tags:
  - status

- name: info service
  debug: 
    msg: 
      - "CONFIG_HOME = /etc/mysql/"
      - "DATA_HOME = /var/lib/mysql"
  tags:
  - info


- name: remove mariadb
  apt: pkg={{ item.name }} state=absent purge=true
  with_items: "{{ _apt }}"
  tags: remove

- name: remove mariadb config
  file: path=/etc/mysql state=absent
  tags: remove

- name: remove mariadb data
  file: path=/var/lib/mysql state=absent
  tags: remove


- name: telegraf add mysql monitoring
  ini_file:
    path: /etc/telegraf/telegraf.conf
    section: "[inputs.mysql]"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { option: "servers", value: ["root:{{ mysql_root_pass }}@tcp(localhost:3306)/?tls=false"] }
  notify: restart-telegraf
  when: telegraf_conf.stat.exists
  tags:
  - install
  - config

- name: telegraf remove mysql monitoring
  ini_file:
    path: /etc/telegraf/telegraf.conf
    section: "[inputs.mysql]"
    state: absent
  when: telegraf_conf.stat.exists
  tags:
  - remove




