- name: add apt key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com
    id: F1656F24C74CD1D8

- name: add repository
  apt_repository:
    repo: deb [arch=amd64,i386,ppc64el] http://ftp.kaist.ac.kr/mariadb/repo/10.1/ubuntu xenial main
    state: present

- name: apt update
  apt:
    update_cache: yes

- name: install mariadb-server
  apt:
    name: mariadb-server
    state: present
    install_recommends: false
  register: mariadb_server_register_install_status

- name: restart mysql service
  service:
    name: mysql
    state: restarted

