- import_tasks: ../common/tasks/main.yml

- name: install keepalived
  apt: pkg={{ item }} state=present
  with_items:
  - keepalived
  tags:
  - install

- name: update sysctl.conf
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  with_dict: "{{ sysctl_setting }}"
  when:
  - sysctl_setting is defined
  tags:
  - install

- name: config keepalived.conf
  template: 
    src: keepalived.conf.j2 
    dest: /etc/keepalived/keepalived.conf 
  notify: restart-keepalived
  tags:
  - install
  - config

- name: remove keepalived
  apt: pkg={{ item }} state=absent purge=true
  with_items:
  - keepalived
  tags:
  - remove

