- import_tasks: ../common/tasks/main.yml

- name: remove lock files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - /var/lib/dpkg/updates/*
#  - /var/lib/apt/lists/lock
#  - /var/cache/apt/archives/lock
  - /var/lib/dpkg/lock 
  tags:
  - install
  
- name: install keepalived
  apt: pkg={{ item }} state=present
  with_items:
  - keepalived
  register: apt_status
  until: apt_status|success
  delay: 5
  retries: 24
  tags:
  - install

- name: config keepalived.conf
  template: 
    src: keepalived.conf.j2 
    dest: /etc/keepalived/keepalived.conf 
  notify: restart-keepalived
  tags:
  - install
  - config

- name: remove keepalived
  apt: pkg={{ item }} state=absent purge=true
  with_items:
  - keepalived
  tags:
  - remove

- name: stop keepalived
  systemd: name=keepalived state=stopped
  tags:
  - stop

- name: start keepalived
  systemd: name=keepalived state=started
  tags:
  - start

- name: restart keepalived
  systemd: name=keepalived state=restarted
  tags:
  - restart
