- name: install keepalived
  apt: pkg={{ item }} state=present
  with_items:
  - keepalived
  tags:
  - install

- name: update sysctl.conf
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: 1
    state: present
    reload: yes
  tags:
  - install

- name: config keepalived.conf
  template: 
    src: keepalived.conf.j2 
    dest: /etc/keepalived/keepalived.conf 
  notify: restart-keepalived
  tags:
  - install
  - config

- name: remove keepalived
  apt: pkg={{ item }} state=absent purge=true
  with_items:
  - keepalived
  tags:
  - remove

