- import_tasks: ../common/tasks/main.yml

- name: remove lock files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - /var/lib/apt/lists/lock
  - /var/cache/apt/archives/lock
  - /var/lib/dpkg/lock 
  - /var/lib/dpkg/updates/*
  tags:
  - install
  
- name: install keepalived
  apt: pkg={{ item }} state=present
  with_items:
  - keepalived
  register: apt_status
  until: apt_status|success
  delay: 5
  retries: 48
  tags:
  - install

- name: config keepalived.conf
  template: 
    src: keepalived.conf.j2 
    dest: /etc/keepalived/keepalived.conf 
  notify: restart-keepalived
  tags:
  - install
  - config

- name: remove keepalived
  apt: pkg={{ item }} state=absent purge=true
  with_items:
  - keepalived
  tags:
  - remove

- name: stop keepalived
  systemd: name=keepalived state=stopped
  tags:
  - stop

- name: start keepalived
  systemd: name=keepalived state=started
  tags:
  - start

- name: restart keepalived
  systemd: name=keepalived state=restarted
  tags:
  - restart

- name: check virutal ip
  shell: ip a | grep "{{ virtual_ipaddress }}" | grep -v grep | awk '{print $2}'
  ignore_errors: yes
  changed_when: false
  register: vip_status
  tags:
  - status

- name: check service
  shell: ps aux | grep keepalived | grep -v grep | awk '{print $2}'
  ignore_errors: yes
  changed_when: false
  register: service_status
  tags:
  - status

- name: status service
  debug: 
    msg: 
      - "keepalived =>  {{ service_status.stdout != ''}} : {{ service_status.stdout }}"
      - "vip_status =>  {{ vip_status.stdout != ''}} : {{ vip_status.stdout }}"
  tags:
  - status

- name: info service
  debug: 
    msg: 
      - "CONFIG_HOME = /etc/keepalived"
  tags:
  - info

