- name: include vars
  include_vars: vars/install.yml
  tags:
  - install
  - config

- name: include vars
  include_vars: vars/remove.yml
  tags:
  - remove

- name: update sysctl.conf
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  with_dict: "{{ sysctl_setting }}"
  when:
  - sysctl_setting is defined
  tags:
  - install
  - remove

#- name: update limits.conf
#  debug: var=limits_setting
#  tags:
#  - install

- name: update limits.conf
  pam_limits:
    domain: "{{ item.split(' ')[0] }}"
    limit_type: "{{ item.split(' ')[1] }}"
    limit_item: "{{ item.split(' ')[2] }}"
    value: "{{ item.split(' ')[3] }}"
  with_items: "{{ limits_setting }}"
  when:
  - limits_setting is defined
  tags:
  - install
  - remove
