#- name: update apt pakcage
#  apt:
#    update_cache: yes
#  tags:
#  - install
# Failed to lock apt for exclusive operation 발생

- name: common file exists
  stat:
    path: vars/install.yml
  register: file_install
  tags:
  - install
  - config

- name: common file exists
  stat:
    path: vars/remove.yml
  register: file_remove
  tags:
  - remove


- name: common include vars
  include_vars: vars/install.yml
  when: file_install.stat.exists
  tags:
  - install
  - config

- name: common include vars
  include_vars: vars/remove.yml
  when: file_remove.stat.exists
  tags:
  - remove

- name: common update sysctl.conf
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  with_dict: "{{ sysctl_setting }}"
  when:
  - sysctl_setting is defined
  tags:
  - install
  - remove

#- name: update limits.conf
#  debug: var=limits_setting
#  tags:
#  - install

- name: common update limits.conf
  pam_limits:
    domain: "{{ item.split(' ')[0] }}"
    limit_type: "{{ item.split(' ')[1] }}"
    limit_item: "{{ item.split(' ')[2] }}"
    value: "{{ item.split(' ')[3] }}"
  with_items: "{{ limits_setting }}"
  when:
  - limits_setting is defined
  tags:
  - install
  - remove

- name: common check if telegraf is installed 
  stat:
    path: /etc/telegraf/telegraf.conf
  register: telegraf_conf
  tags:
  - install
  - config
  - remove
